on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: wei/curl@v1
      with:
        args: -d 'token=${{ secrets.TOKEN_ADDR_1 }}' -X POST http://121.196.175.55:5711
